/*
Enter your query here.
*/

SELECT 
CONTESTS.CONTEST_ID,
CONTESTS.HACKER_ID,
CONTESTS.NAME,
SUM(CHALLENGE_STATS.SUM_SUBMISSIONS),
SUM(CHALLENGE_STATS.SUM_ACCPT_SUBMISSIONS),
SUM(CHALLENGE_STATS.SUM_TOTAL_VIEWS),
SUM(CHALLENGE_STATS.SUM_TOTAL_UNIQUE_VIEWS)

FROM
CONTESTS LEFT JOIN COLLEGES ON (CONTESTS.CONTEST_ID = COLLEGES.CONTEST_ID)
LEFT JOIN
                                
(SELECT CHALLENGES.COLLEGE_ID,
SUB_SUM.SUM_SUBMISSIONS,
SUB_SUM.SUM_ACCPT_SUBMISSIONS, 
VIEW_SUM.SUM_TOTAL_VIEWS,
VIEW_SUM.SUM_TOTAL_UNIQUE_VIEWS

FROM
CHALLENGES
LEFT JOIN 
/* SUM SUBMISSION_STATS */
(SELECT SUBMISSION_STATS.CHALLENGE_ID,
SUM(SUBMISSION_STATS.TOTAL_SUBMISSIONS) AS SUM_SUBMISSIONS,
SUM(SUBMISSION_STATS.TOTAL_ACCEPTED_SUBMISSIONS) AS SUM_ACCPT_SUBMISSIONS
FROM SUBMISSION_STATS
GROUP BY 
SUBMISSION_STATS.CHALLENGE_ID) SUB_SUM ON (CHALLENGES.CHALLENGE_ID = SUB_SUM.CHALLENGE_ID)
LEFT JOIN
/* SUM VIEW_STATS */
(SELECT VIEW_STATS.CHALLENGE_ID,
SUM(VIEW_STATS.TOTAL_VIEWS) SUM_TOTAL_VIEWS,
SUM(VIEW_STATS.TOTAL_UNIQUE_VIEWS) SUM_TOTAL_UNIQUE_VIEWS

FROM VIEW_STATS
GROUP BY
VIEW_STATS.CHALLENGE_ID) VIEW_SUM

ON (CHALLENGES.CHALLENGE_ID = VIEW_SUM.CHALLENGE_ID)) CHALLENGE_STATS
ON (CHALLENGE_STATS.COLLEGE_ID = COLLEGES.COLLEGE_ID)
GROUP BY 
CONTESTS.CONTEST_ID,
CONTESTS.HACKER_ID,
CONTESTS.NAME

HAVING
SUM(CHALLENGE_STATS.SUM_SUBMISSIONS)+
SUM(CHALLENGE_STATS.SUM_ACCPT_SUBMISSIONS)+
SUM(CHALLENGE_STATS.SUM_TOTAL_VIEWS)+
SUM(CHALLENGE_STATS.SUM_TOTAL_UNIQUE_VIEWS) > 0

ORDER BY
CONTESTS.CONTEST_ID


