SELECT DISTINCT
ONE.X, ONE.Y
FROM FUNCTIONS ONE, FUNCTIONS TWO
WHERE
ONE.X = TWO.Y AND ONE.Y = TWO.X
AND
((ONE.X != ONE.Y)
	OR
	1 < (SELECT COUNT(*) FROM FUNCTIONS THREE WHERE THREE.X = ONE.X AND THREE.Y = ONE.Y)_
AND ONE.X <= ONE.Y
ORDER BY 
ONE.X

