SELECT X, Y FROM (
SELECT X, Y, COUNT(*) AS CTR FROM (

(SELECT X, Y FROM FUNCTIONS WHERE 
X IN 
(SELECT X FROM FUNCTIONS WHERE X IN (SELECT Y FROM FUNCTIONS))
 AND
Y IN
(SELECT Y FROM FUNCTIONS WHERE Y IN (SELECT X FROM FUNCTIONS))
AND
X<Y)

UNION ALL

(SELECT X,Y FROM FUNCTIONS)) SUB1
GROUP BY X, Y
HAVING CTR > 1) SUB2


