SELECT X, Y FROM (

SELECT X, Y FROM FUNCTIONS WHERE Y IN 
    (SELECT X FROM FUNCTIONS)
INTERSECT
SELECT X,Y FROM FUNCTIONS WHERE X IN 
    (SELECT Y FROM FUNCTIONS)
) TBL1
WHERE X < Y
UNION ALL
SELECT X, Y FROM 
(SELECT X, Y, COUNT(*) AS CTR FROM (
SELECT X, Y FROM FUNCTIONS WHERE Y IN
(SELECT X FROM FUNCTIONS)
UNION ALL
SELECT X, Y FROM FUNCTIONS WHERE X IN
(SELECT Y FROM FUNCTIONS)) SUB
GROUP BY X, Y
HAVING CTR > 2) SUB
ORDER BY X ASC
